DEVICE: 'cuda:3'
RANDOM_SEED: 42

MODEL:
  N_LAYERS: 8
  N_HEADS: 8
  N_EMBD: 256
  MAX_LEN: 100
  NUM_PROPS: 0
  EMBD_PDROP: 0.1
  RESID_PDROP: 0.1
  ATTN_PDROP: 0.1
  VOCAB_SIZE: 94

GENERATE:
  CONTEXT: C
  BATCH_SIZE: 200
  N_CPU: 1
  VERSION: nc
  TEMPERATURE: 1.0
  TEMPLATES: 
  TOTAL: 1.0e+3
  CKPT_PATH: weights/guacamol_nc.pt
  OUTPUT: output/generate_nc/out.smi