DEVICE: 'cuda:0'
RANDOM_SEED: 2023

MODEL:
  N_LAYERS: 8
  N_HEADS: 8
  N_EMBD: 256
  MAX_LEN: 100
  NUM_PROPS: 72
  EMBD_PDROP: 0.1
  RESID_PDROP: 0.1
  ATTN_PDROP: 0.1
  VOCAB_SIZE: 94

GENERATE:
  CONTEXT: C
  BATCH_SIZE: 1024
  N_CPU: 1
  VERSION: pc
  TEMPERATURE: 0.7
  TEMPLATES: ['C[NH+]1CCN(C2=CC=C(OC(F)(F)F)C(NC3=NC=C(CCC4=C5N(CCO)N=C4C(N)=O)C5=N3)=C2)CC1']
  OUTPUT: output/generate_pc/out.smi
  CKPT_PATH: weights/guacamol_BM_72bit_0410.pt
  TOTAL: 1.0e+6
